services:
    apwa.attachcount.listener:
        class: apwa\attachcount\event\listener
        arguments:
            - '@config'
            - '@template'
        tags:
            - { name: event.listener }
